/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
/* Header for class com_wzf_ffmpeg_VideoUtils */

#ifndef _Included_com_wzf_ffmpeg_VideoUtils
#define _Included_com_wzf_ffmpeg_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzf_ffmpeg_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_wzf_ffmpeg_VideoUtils
 * Method:    getVideoInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ffmpeg_VideoUtils_getVideoInfo
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_playSimpleVideo
        (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_playSimpleAudio
        (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_playSimpleAudioForOpensl
        (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_threadTest
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_initThread
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_destroyThread
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_play
        (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
