/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzf_ffmpeg_VideoUtils */

#ifndef _Included_com_wzf_ffmpeg_VideoUtils
#define _Included_com_wzf_ffmpeg_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzf_ffmpeg_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_wzf_ffmpeg_VideoUtils
 * Method:    getVideoInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ffmpeg_VideoUtils_getVideoInfo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
