/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_dongnaoedu_dnffmpegplayer_VideoUtils */
/*
 * Class:     com_dongnaoedu_dnffmpegplayer_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wzf_ffmpeg_VideoUtils_decode
        (JNIEnv *, jclass, jstring, jstring);
